version: '3'
services: 
  jupyter:
    build: ./
    image: dbmi/fair_jupyter_r_nhanes
    networks:
      - public
    expose: 
      - 8888
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work/

networks:
  public: