version: '3.3'
services:

  # nginx
  nginx:
    image: dbmi/nginx:${nginx_version}
    restart: always
    networks:
      - public

  # jupyter 
  jupyter:
    build: ./jupyter
    image: dbmi/r-datascience-notebook:nhanes-pic-sure-notebook-Aug-13-2018
    env_file:
      - ${ENV_FILE}
    restart: always
    depends_on:
      - nginx
      - db
      - irct
    networks:
      - public
    expose:
      - 8888
    ports:
      - 80:8888
    volumes:
      - ./jupyter-notebooks:/home/jovyan/work

  # i2b2transmart database
  db:
    image: dbmi/i2b2transmart-db:${db_version}
    restart: always
    networks:
      - public
    expose:
      - 1521
    # i2b2transmart database exposed port
    ports:
      - ${DOCKER_DB_PORT:-1521}:1521

  ## PIC-SURE API Stack ##
  # IRCT
  irct:
    image: dbmi/irct:${irct_version}
    depends_on:
        - irctdb
        - nginx
        - i2b2-wildfly
    env_file:
        - ${ENV_FILE}
    restart: always
    networks:
      - public
    expose:
        - 8080
    ports:
      - 8080:8080

  # PIC-SURE i2b2-wildfly resource
  i2b2-wildfly:
    image: dbmi/i2b2-wildfly:${i2b2_wildfly_version}
    env_file:
      - ${ENV_FILE}
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    restart: always
    networks:
      - public
    expose:
      - 9090
    ports:
      - 9090:9090

  # IRCT DB
  irctdb:
    image: dbmi/irct-db:${irctdb_version}
    env_file:
        - ${ENV_FILE}
    restart: always
    command: --datadir=/mysql/data
    networks:
      - public
    expose:
        - 3306
    # PIC-SURE database exposed port
    ports:
        - ${DOCKER_IRCT_DB_PORT:-3306}:3306

networks:
  public:
